name: Deploy Blog

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: docker
    container: 
      image: node:20-bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and run Confgen and setup tree-sitter-cli 
        run: |
          apt update
          apt install -y curl libluajit-5.1-2 unzip

          curl -L https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v0.22.6.zip -o tree-sitter.zip
          unzip tree-sitter.zip -d /tmp/tree-sitter

          curl -L https://git.mzte.de/LordMZTE/confgen/releases/download/v0.3.1/confgen-linux-x86_64.zip -o confgen.zip
          unzip confgen.zip -d /tmp/confgen

          /tmp/confgen/bin/confgen confgen.lua _site/
      - name: Rsync deployments
        uses: https://github.com/burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: _site/
          remote_path: ${{ secrets.SSH_PUBLIC_PATH }} 
          remote_host: coding-agent.me
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
      # this is a workaround the rsync which deletes assets folder
      - name: Deploy assets
        uses: https://github.com/JimCronqvist/action-ssh@1.0.0
        with:
          hosts: '${{ secrets.SSH_USER }}@coding-agent.me:${{ secrets.SSH_PORT }}'
          privateKey: ${{ secrets.DEPLOY_KEY }}
          debug: false
          command: cp -r ${{ secrets.SSH_ASSETS_PATH }} ${{ secrets.SSH_PUBLIC_PATH }} 
