name: Deploy Blog

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: docker
    container: 
      image: node:20-bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and run Confgen
        run: |
          apt update
          apt install -y curl libluajit-5.1-2 unzip
          curl -L https://git.mzte.de/LordMZTE/confgen/releases/download/v0.2.2/confgen-linux-x86_64.zip -o confgen.zip
          unzip confgen.zip -d /tmp/confgen
          /tmp/confgen/bin/confgen confgen.lua _site/
  deploy:
    runs-on: docker
    container: 
      image: node:20-bookworm
    needs: build
    steps:
    - name: rsync deployments
      uses: github.com/burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: _site/
        remote_path: /home/u111113374/public_html
        remote_host: coding-agent.me
        remote_user: u111113374
        remote_key: ${{ secrets.DEPLOY_KEY }}
